### ISSUE TITLE
Instead of completing tasks, it just says it will begin research, but never does.

### ISSUE THREAD

**Issue by pseudotensor** [microsoft/TaskWeaver#103]
![image](https://github.com/microsoft/TaskWeaver/assets/2249614/6df3d1e3-c078-4baa-892a-7fc6d2fe1828)

**Comment by ShilinHe** [comment]
Thanks for your interests in trying TaskWeaver.
TaskWeaver is designed for data analysis tasks and domain specific scenarios via writing code. In your case, if checking the step details, you will find that only the Planner is invoked. That means, no code is generated, all these responses are based on the LLMs' own knowledge. To make it perform better, a web search plugin should be provided so that TaskWeaver can search the internet for more information.
