### ISSUE TITLE
Can TaskWeaver do the indexing part (loading, splitting, storing)?

### ISSUE THREAD

**Issue by ligjn** [microsoft/TaskWeaver#118]
**Is your feature request related to a problem? Please describe.**
I want to use the document Q&A feature of TaskWeaver. Can TaskWeaver do the indexing part (loading, splitting, storing)?

**Describe alternatives you've considered**
Indexing documents first like LangChain (loading, splitting, storing)，Or can I only use TaskWeaver to implement plugins for Retrieval and generation?

**Comment by ShilinHe** [comment]
Hi @ligjn, Thanks for your question! Currently, indexing is not included in TaskWeaver since this part is relatively independent and does not rely on human interaction. We would recommend first build an indexing application (many existing work) and incorporate the document retrieval and generation with TaskWeaver as a plugin.

**Comment by ligjn** [comment]
Okay, I understand
