### ISSUE TITLE
How do I pass the user's query directly to the plugin without modification?

### ISSUE THREAD

**Issue by lingxiaaisuixin** [microsoft/TaskWeaver#286]
I have a plugin that queries the data, and the plugin has a parameter that accepts the user's questions. Often the user question received by the plugin has been modified, and I expect the parameter received by the plugin to be the original user question. For example, if the user asks' what's the weather like today ', I want the plugin to receive 'what's the weather like today' as well. I tried to change the planner examples and code interpreter examples but sometimes it also changed the user questions. I hope you can give me some advice.

**Comment by liqul** [comment]
This is an interesting case but I don't think there is a direct path from the user to the plugins. The user query needs at least to be passed to LLM once before reaching the plugins so it is hard to fix the behavior of the LLM in filling the plugin arguments. Probably, you can optimize your plugin design in defining a more concrete input instead of a sentence in natural language. Given your example of "what's the weather like today", you can define it as `weather(date="today")` instead of using NL.

**Comment by lingxiaaisuixin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
 谢谢！
