### ISSUE TITLE
How to set data and its descriptions without prompting in each session to load data

### ISSUE THREAD

**Issue by Haxeebraja** [microsoft/TaskWeaver#391]
I do not want to load the data file from plugin each time the session start. I am looking for a way to directly start asking questions about data. 

Secondly, where can we set description about data and columns that would help TaskWeaver to pull the right columns each time on a prompt?

**Comment by liqul** [comment]
I don't quite understand your requirement. So, you mean that you only want to process a specific data file instead of loading a dynamic data file? 

If this is what you want and you are using Taskweaver as a library, you can hardcode a message to the application asking it to load a file and display its data schema, which should solve your problem. Otherwise, you may need to modify some code of Taskweaver.

**Comment by lolapirespintopolarys** [comment]
@Haxeebraja Hello! I want to do the exact same things. Did you find a way to do it ? :)

**Comment by Haxeebraja** [comment]
I managed to directly start asking questions by setting up instructions in planner prompt file. 

While the data file still gets loaded in each new session, I no longer need to explicitly instruct Taskweaver to load it at the start. Secondly, it better understands data file's structure. 

I recommend to the team further enhancements to fully optimize this functionality.
