### ISSUE TITLE
how to debug  the TaskWeaver in pycharm step by step ?

### ISSUE THREAD

**Issue by pily1** [microsoft/TaskWeaver#404]
hi everyone:
    I can lanuch the TaskWeaver in terminal use this command "python -m taskweaver -p ./project/",now I want to debug it step by step with pycharm ?
how can I do it ?

**Comment by liqul** [comment]
This is quite staightforward. Create a new run profile, e.g., named 'taskweaver'.

Select `module` instead of `script` for the type and set the `Working directory` to the project folder.

![image](https://github.com/user-attachments/assets/58c14f1d-8f27-4baa-b070-4606bfdc83a2)

Then, you can debug it step by step.

**Comment by pily1** [comment]
think you,I get it
