### ISSUE TITLE
Runing with transformer model loader on oobabooga/text-generation-webui problem

### ISSUE THREAD

**Issue by Wintoplay** [microsoft/TaskWeaver#83]
I cannot use taskweaver on api hosted by oobabooga/text-generation-webui. However, it work with llama cpp model loader on oobabooga/text-generation-webui which I cannot use it well as AMD rocm 5.7 has power draw bug. So I need to get this thing work with transfromers model loader.

![image](https://github.com/microsoft/TaskWeaver/assets/66968226/f1a6f153-4285-459f-a101-ada47583a867)

Why do i get this error?

AssertionError: send_to field is None
Exception: Planner failed to generate response because send_to field is None

**Comment by ShilinHe** [comment]
The issue of `"send_to" field is None` is usually caused by the incorrect LLM response. In TaskWeaver, the response is expected to follow a predefined schema (in `json`). However, if the LLM does not follow the instruction, the error would happen. A possible solution is to use a more powerful model.
